import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import WtsupBtn from "@/components/WtsupBtn";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Arik Tattoo",
  description: "Generated by Arik Alexandrov - arikxl",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-900 min-h-full text-white `}
      >
        {/* <Header /> */}

        {/* <WtsupBtn /> */}
        <main className='mx-auto min-h-[100vh] overflow-x-hidden'>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
