import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import StickyHeader from "@/components/StickyHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["hebrew", "latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["hebrew", "latin"],
});

export const metadata: Metadata = {
  title: "Arik Tattoo",
  description: "Generated by Arik Alexandrov - arikxl",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="he" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-900 min-h-full text-white `}
      >

        {/* <div className="block md:hidden fixed top-0 left-0 z-50 text-slate-700 bg-white shadow-md animate-fade-down w-full">
          <Header />
        </div> */}
        <main className='mx-auto min-h-[100vh] overflow-x-hidden'>
        {children}
        </main>
        {/* <div className=" hidden md:block">

          <StickyHeader />
        </div> */}
        <Footer />
      </body>
    </html>
  );
}
